
// Location data for demonstration
export const locationData = [
  { state: 'AK', city: 'Anchorage', full_name: 'Anchorage, AK' },
  { state: 'AL', city: 'Huntsville', full_name: 'Huntsville, AL' },
  { state: 'AL', city: 'Birmingham', full_name: 'Birmingham, AL' },
  { state: 'AL', city: 'Montgomery', full_name: 'Montgomery, AL' },
  { state: 'AL', city: 'Mobile', full_name: 'Mobile, AL' },
  { state: 'AL', city: 'Tuscaloosa', full_name: 'Tuscaloosa, AL' },
  { state: 'AR', city: 'Little Rock', full_name: 'Little Rock, AR' },
  { state: 'AR', city: 'Fayetteville', full_name: 'Fayetteville, AR' },
  { state: 'AZ', city: 'Phoenix', full_name: 'Phoenix, AZ' },
  { state: 'AZ', city: 'Tucson', full_name: 'Tucson, AZ' },
  { state: 'AZ', city: 'Mesa', full_name: 'Mesa, AZ' },
  { state: 'AZ', city: 'Chandler', full_name: 'Chandler, AZ' },
  { state: 'AZ', city: 'Gilbert', full_name: 'Gilbert, AZ' },
  { state: 'AZ', city: 'Glendale', full_name: 'Glendale, AZ' },
  { state: 'AZ', city: 'Scottsdale', full_name: 'Scottsdale, AZ' },
  { state: 'AZ', city: 'Peoria', full_name: 'Peoria, AZ' },
  { state: 'AZ', city: 'Tempe', full_name: 'Tempe, AZ' },
  { state: 'AZ', city: 'Surprise', full_name: 'Surprise, AZ' },
  { state: 'AZ', city: 'Goodyear', full_name: 'Goodyear, AZ' },
  { state: 'AZ', city: 'Buckeye', full_name: 'Buckeye, AZ' },
  { state: 'AZ', city: 'Yuma', full_name: 'Yuma, AZ' },
  { state: 'CA', city: 'Los Angeles', full_name: 'Los Angeles, CA' },
  { state: 'CA', city: 'San Diego', full_name: 'San Diego, CA' },
  { state: 'CA', city: 'San Jose', full_name: 'San Jose, CA' },
  { state: 'CA', city: 'San Francisco', full_name: 'San Francisco, CA' },
  { state: 'CA', city: 'Fresno', full_name: 'Fresno, CA' },
];
