// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables for Supabase connection
const SUPABASE_URL = import.meta.env.VITE_PUBLIC_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_PUBLIC_SUPABASE_KEY || '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to log errors from Supabase operations
export const handleSupabaseError = (error: any, operation: string) => {
  if (error) {
    console.error(`Error during ${operation}:`, error.message);
    return error.message;
  }
  return null;
};

// Keep track of successful and failed queries to monitor health
let queryStats = {
  successful: 0,
  failed: 0,
  lastError: null as string | null,
  lastSuccessTime: null as number | null
};

/**
 * Reset query stats
 */
export const resetQueryStats = () => {
  queryStats = {
    successful: 0,
    failed: 0,
    lastError: null,
    lastSuccessTime: null
  };
};

/**
 * Get Supabase query statistics
 */
export const getQueryStats = () => {
  return {
    ...queryStats,
    success_rate: queryStats.successful + queryStats.failed > 0 
      ? (queryStats.successful / (queryStats.successful + queryStats.failed) * 100).toFixed(2) + '%' 
      : 'N/A'
  };
};

/**
 * Wrapper for Supabase queries to track performance and errors
 */
export const trackedQuery = async <T>(
  queryFn: () => Promise<T>,
  operation: string
): Promise<T> => {
  try {
    const result = await queryFn();
    queryStats.successful += 1;
    queryStats.lastSuccessTime = Date.now();
    return result;
  } catch (error) {
    queryStats.failed += 1;
    queryStats.lastError = error instanceof Error ? error.message : String(error);
    console.error(`Error during ${operation}:`, error);
    throw error;
  }
};
